#!/usr/bin/env bash
set -euo pipefail

usage() {
  echo "usage: $0 <g0401-ip|auto> <output-file> [duration-seconds]" >&2
  exit 2
}

[[ $# -ge 2 && $# -le 3 ]] || usage
candidate_ip="$1"
output_file="$2"
duration="${3:-30}"

router_host="${MYQ_ROUTER_HOST:-}"
router_port="${MYQ_ROUTER_PORT:-1222}"
router_user="${MYQ_ROUTER_USER:-admin}"
router_key="${MYQ_ROUTER_KEY:-$HOME/.ssh/id_rsa}"

[[ -n "$router_host" ]] || {
  echo "MYQ_ROUTER_HOST must be set" >&2
  exit 2
}
if [[ "$candidate_ip" != "auto" ]]; then
  [[ "$candidate_ip" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]] || usage
fi
[[ "$duration" =~ ^[0-9]+$ ]] || usage
mkdir -p "$(dirname "$output_file")"
ssh_opts=(
  -o BatchMode=yes
  -o ConnectTimeout=5
  -o IdentitiesOnly=yes
  -i "$router_key"
  -p "$router_port"
)

ssh "${ssh_opts[@]}" "$router_user@$router_host" \
  "sh -s -- '$candidate_ip' '$duration'" >"$output_file" <<'REMOTE'
set -u
candidate_ip="$1"
duration="$2"

if [ "$candidate_ip" = "auto" ]; then
  sources="$(cat /proc/net/nf_conntrack 2>/dev/null | grep "dport=8883" | sed -n "s/.*src=\([^ ]*\).*dport=8883.*/\1/p" | sort -u)"
  count="$(printf "%s\n" "$sources" | sed "/^$/d" | wc -l)"
  if [ "$count" -ne 1 ]; then
    echo "# auto-detect-failed: expected exactly one outbound-8883 source"
    exit 3
  fi
  candidate_ip="$sources"
fi

echo "## conntrack"
if [ -r /proc/net/nf_conntrack ]; then
  grep -F "src=$candidate_ip " /proc/net/nf_conntrack 2>/dev/null || true
elif command -v conntrack >/dev/null 2>&1; then
  conntrack -L 2>/dev/null | grep -F "src=$candidate_ip " || true
else
  echo "# conntrack-unavailable"
fi
echo "## logread"
if command -v logread >/dev/null 2>&1; then
  logread 2>/dev/null | grep -F "$candidate_ip" | tail -n 500 || true
else
  echo "# logread-unavailable"
fi

echo "## tcpdump"
if command -v tcpdump >/dev/null 2>&1; then
  if command -v timeout >/dev/null 2>&1; then
    timeout "$duration" tcpdump -i any -nn -l -s 0 "host $candidate_ip" 2>&1 || true
  else
    echo "# tcpdump-present-but-timeout-unavailable"
  fi
else
  echo "# tcpdump-unavailable"
fi
REMOTE

printf 'wrote passive capture: %s\n' "$output_file"
printf 'no router settings changed; no traffic generated by this script\n'
